import 'package:flutter/material.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static AppStrings of(BuildContext context) {
    return AppStrings(Localizations.localeOf(context));
  }

  bool get _isZh => locale.languageCode == 'zh';

  String get workout => _isZh ? '训练' : 'Workout';
  String get plan => _isZh ? '计划' : 'Plan';
  String get diet => _isZh ? '饮食' : 'Diet';
  String get dietTitle => _isZh ? '饮食分析' : 'Diet';
  String get addMeal => _isZh ? '添加餐食' : 'Add Meal';
  String get manualRecord => _isZh ? '手动记录' : 'Manual Only';
  String get meals => _isZh ? '餐食' : 'Meals';
  String get noMealsYet => _isZh ? '还没有饮食记录' : 'No meals yet';
  String get breakfast => _isZh ? '早餐' : 'Breakfast';
  String get lunch => _isZh ? '午餐' : 'Lunch';
  String get dinner => _isZh ? '晚餐' : 'Dinner';
  String get snack => _isZh ? '加餐' : 'Snack';
  String get calories => _isZh ? '热量' : 'Calories';
  String get protein => _isZh ? '蛋白' : 'Protein';
  String get carbs => _isZh ? '碳水' : 'Carbs';
  String get fat => _isZh ? '脂肪' : 'Fat';
  String get mealTitle => _isZh ? '标题' : 'Title';
  String get notes => _isZh ? '备注' : 'Notes';
  String get photo => _isZh ? '照片' : 'Photo';
  String get nutrition => _isZh ? '营养' : 'Nutrition';
  String get pendingAnalysis => _isZh ? '待分析' : 'Pending';
  String get aiAnalyzed => _isZh ? 'AI 分析' : 'AI';
  String get manualEntry => _isZh ? '手动补全' : 'Manual';
  String get analysisFailed => _isZh ? '分析失败' : 'Failed';
  String get removeEntry => _isZh ? '删除记录' : 'Delete Entry';
  String get photoUnavailable => _isZh ? '照片不可用' : 'Photo unavailable';
  String get addPhotoFailed => _isZh ? '无法添加照片' : 'Unable to add photo';
  String get untitledMeal => _isZh ? '未命名餐食' : 'Untitled Meal';
  String get aiAnalysis => _isZh ? '大模型分析' : 'AI Analysis';
  String get aiProvider => _isZh ? 'API 提供商' : 'API Provider';
  String get aiApiKey => _isZh ? 'API 密钥' : 'API Key';
  String get aiBaseUrl => _isZh ? 'Base URL' : 'Base URL';
  String get aiModel => _isZh ? '模型' : 'Model';
  String get aiEnabled => _isZh ? '已启用' : 'Enabled';
  String get aiDisabled => _isZh ? '未启用' : 'Disabled';
  String get aiOpenAi => _isZh ? 'OpenAI' : 'OpenAI';
  String get aiSiliconFlow => _isZh ? 'SiliconFlow' : 'SiliconFlow';
  String get aiOpenAiCompatible => _isZh ? '兼容 OpenAI' : 'OpenAI-compatible';
  String get aiSaveSettings => _isZh ? '保存 AI 设置' : 'Save AI Settings';
  String get aiClearSettings => _isZh ? '清空 AI 设置' : 'Clear';
  String get aiTestConnection => _isZh ? '测试连接' : 'Test Connection';
  String get aiSettingsSaved => _isZh ? 'AI 设置已保存' : 'AI settings saved';
  String get aiConnectionSuccess => _isZh ? '连接成功' : 'Connection succeeded';
  String get aiConnectionFailed => _isZh ? '连接失败' : 'Connection failed';
  String get aiSettingsHint => _isZh ? '必须填写提供商、API 密钥和模型，才能启用饮食图片分析。' : 'Provider, API key, and model are required before image analysis can be enabled.';
  String get aiCompatibleHint => _isZh ? '兼容接口请填写完整的 Base URL，通常应包含 /v1。' : 'For compatible providers, enter the full base URL, usually including /v1.';
  String get aiSiliconFlowHint => _isZh ? 'SiliconFlow 使用 /chat/completions，建议选择视觉模型，例如 Qwen/Qwen2.5-VL-32B-Instruct。' : 'SiliconFlow uses /chat/completions. Choose a vision model such as Qwen/Qwen2.5-VL-32B-Instruct.';
  String get aiSecurityHint => _isZh ? '密钥会保存在本机和备份文件中，请自行承担风险。' : 'The key is stored locally and included in backups. Use at your own risk.';
  String get aiIncompleteSettings => _isZh ? '请先完整填写提供商、API 密钥和模型。' : 'Complete provider, API key, and model first.';
  String get aiManualOnlyHint => _isZh ? '当前未启用大模型分析，只能手动记录。' : 'AI analysis is disabled. Manual logging only.';
  String get aiReadyHint => _isZh ? '已启用图片分析，新餐食会自动尝试识别。' : 'Image analysis is enabled. New meals will be analyzed automatically.';
  String get aiProviderNotChosen => _isZh ? '未选择' : 'Not selected';
  String get analysisErrorTitle => _isZh ? '失败详情' : 'Failure Details';
  String get analysisErrorEmpty => _isZh ? '没有拿到额外错误信息。' : 'No additional error details.';
  String get analysisFailurePrefix => _isZh ? '分析失败：' : 'Analysis failed: ';
  String get settings => _isZh ? '设置' : 'Settings';
  String get about => _isZh ? '关于' : 'About';
  String get aboutStorageHint => _isZh ? '数据保存在本地，更新应用后仍会保留。' : 'Data is stored locally and will remain after updates.';

  String get planSettings => _isZh ? '计划设置' : 'Plan Settings';
  String get languageSetting => _isZh ? '语言' : 'Language';
  String get languageSettingLabel => _isZh ? 'Language / 语言' : 'Language / 语言';
  String get followSystem => _isZh ? '跟随系统' : 'System';
  String get chineseSimplified => _isZh ? '中文（简体）' : 'Chinese (Simplified)';
  String get english => _isZh ? '英文' : 'English';

  String get noPlansYet => _isZh ? '暂无计划，点击 + 创建' : 'No plans yet. Tap + to create one.';
  String get newPlan => _isZh ? '新建计划' : 'NEW PLAN';
  String get editPlan => _isZh ? '编辑计划' : 'EDIT PLAN';
  String get planName => _isZh ? '计划名称' : 'Plan name';
  String get exercise => _isZh ? '动作' : 'Exercise';
  String get exerciseName => _isZh ? '动作名称' : 'Exercise name';
  String get exerciseType => _isZh ? '动作类型' : 'Exercise Type';
  String get freeExercise => _isZh ? '自定义动作' : 'Custom Exercise';
  String get weightedExercise => _isZh ? '负重动作' : 'Weighted Exercise';
  String get timedExercise => _isZh ? '计时动作' : 'Timed Exercise';
  String get customFields => _isZh ? '自定义字段' : 'Custom Fields';
  String get fieldName => _isZh ? '字段名' : 'Field Name';
  String get fieldValue => _isZh ? '字段值' : 'Field Value';
  String get addField => _isZh ? '+ 添加字段' : '+ Add Field';
  String weightLabel(String unit) => _isZh ? '重量（$unit）' : 'Weight ($unit)';
  String get weightUnitSetting => _isZh ? '重量单位' : 'Weight Unit';
  String get kilograms => _isZh ? '千克（kg）' : 'Kilograms (kg)';
  String get pounds => _isZh ? '磅（lb）' : 'Pounds (lb)';
  String get reps => _isZh ? '次数' : 'Reps';
  String get count => _isZh ? '个数' : 'Count';
  String get duration => _isZh ? '时间（秒）' : 'Duration (sec)';
  String get distance => _isZh ? '距离' : 'Distance';
  String get sets => _isZh ? '组数' : 'Sets';
  String get addExercise => _isZh ? '+ 添加动作' : '+ Add Exercise';
  String get savePlan => _isZh ? '保存计划' : 'SAVE PLAN';
  String get pleaseEnterPlanName => _isZh ? '请输入计划名称' : 'Please enter plan name';
  String get completeExerciseFields => _isZh ? '请完善动作信息' : 'Please complete all exercise fields';

  String get selectPlan => _isZh ? '选择计划' : 'SELECT PLAN';
  String get noPlanTemplatesYet => _isZh ? '暂无计划模板' : 'No plan templates yet.';
  String get goToPlanSettings => _isZh ? '去计划设置' : 'Go to Plan Settings';
  String get schedule => _isZh ? '日程' : 'SCHEDULE';
  String get history => _isZh ? '历史' : 'History';
  String get planDetails => _isZh ? '计划详情' : 'PLAN DETAILS';
  String get viewPlanDetails => _isZh ? '查看详情' : 'View Details';
  String get noPlanDetails => _isZh ? '该日期暂无可展示的具体动作' : 'No detailed exercises for this day';
  String get restDay => _isZh ? '休息日' : 'Rest Day';
  String get planDeleted => _isZh ? '计划已删除' : 'Plan deleted';
  String get greatJob => _isZh ? '干得漂亮！' : 'Great job!';
  String get completedAllPlans => _isZh ? '今天的计划已全部完成，加油！' : "You've completed all plans for today. Keep it up!";
  String get ok => _isZh ? '好的' : 'OK';

  String get todaysSession => _isZh ? '今日训练' : "TODAY'S SESSION";
  String get noHistoryYet => _isZh ? '还没有历史训练记录' : 'No workout history yet';
  String get days => _isZh ? '天' : 'Days';
  String get restRecover => _isZh ? '休息与恢复' : 'Rest & Recover';
  String get restingWait => _isZh ? '休息中，请稍候' : 'Resting... Please wait';
  String get restFinished => _isZh ? '休息结束！' : 'Rest Finished!';
  String get timeForNextSet => _isZh ? '该进行下一组了！' : 'Time for the next set!';
  String get gotIt => _isZh ? '知道了' : 'GOT IT';
  String get addSet => _isZh ? '新增一组' : 'Add Set';
  String get editSet => _isZh ? '编辑一组' : 'Edit Set';
  String get cancel => _isZh ? '取消' : 'CANCEL';
  String get add => _isZh ? '添加' : 'ADD';
  String get save => _isZh ? '保存' : 'SAVE';
  String get pleaseEnterValidNumbers => _isZh ? '请输入有效数字' : 'Please enter valid numbers';
  String get pleaseSelectPlanFirst => _isZh ? '请先选择今天的计划' : 'Please select a plan for today first';
  String get addExtraExercise => _isZh ? '添加额外动作' : 'ADD EXTRA EXERCISE';
  String get editExtraExercise => _isZh ? '编辑额外动作' : 'EDIT EXTRA EXERCISE';
  String get restingTitle => _isZh ? '休息中...' : 'Resting...';
  String get countdownInProgress => _isZh ? '倒计时进行中' : 'Countdown in progress';

  String get restTimeOverTitle => _isZh ? '休息结束！🏋️' : 'Rest Time Over! 🏋️';
  String get restTimeOverBody => _isZh ? '该进行下一组了！' : 'Time for your next set!';
  String get restLabel => _isZh ? '休息' : 'REST';
  String get selectRestTime => _isZh ? '选择休息时间' : 'Select Rest Time';
  String get skipRest => _isZh ? '跳过休息' : 'Skip Rest';

  String restSeconds(int seconds) => _isZh ? '$seconds 秒' : '${seconds}s';

  String get soundSetting => _isZh ? '铃声' : 'Sound';
  String get restSoundSetting => _isZh ? '休息铃声' : 'Rest Sound';
  String get chooseSound => _isZh ? '选择铃声' : 'Choose Sound';
  String get previewSound => _isZh ? '试听铃声' : 'Preview';
  String get stopPreview => _isZh ? '停止试听' : 'Stop Preview';
  String get defaultSound => _isZh ? '默认铃声' : 'Default';
  String get resetDefault => _isZh ? '恢复默认' : 'Reset';
  String get soundSelected => _isZh ? '已选择' : 'Selected';
  String get invalidSoundFile => _isZh ? '无法使用该音频文件' : 'Unable to use this audio file';
  String get soundPreviewFailed => _isZh ? '铃声试听失败' : 'Unable to preview this sound';
  String get soundForForegroundAndBackground => _isZh ? '前台倒计时与后台提醒都会使用该铃声' : 'Used for both in-app and background rest alarms';

  String get appearanceSetting => _isZh ? '配色' : 'Appearance';
  String get themeSchemeSetting => _isZh ? '配色方案' : 'Color Scheme';
  String get backgroundImageSetting => _isZh ? '背景图片' : 'Background Image';
  String get chooseBackgroundImage => _isZh ? '选择背景图' : 'Choose Image';
  String get clearBackgroundImage => _isZh ? '清除背景图' : 'Clear Image';
  String get noBackgroundImage => _isZh ? '未设置背景图' : 'No background image';
  String get backgroundImageSelected => _isZh ? '当前背景' : 'Current Background';
  String get backgroundOverlay => _isZh ? '遮罩强度' : 'Overlay';
  String get backgroundBlur => _isZh ? '模糊程度' : 'Blur';
  String get backgroundImageHint => _isZh ? '背景图会在全局生效，并自动叠加深色遮罩以保证可读性' : 'The image is applied globally with a dark overlay for readability';
  String get customThemeScheme => _isZh ? '自定义方案' : 'Custom Scheme';
  String get accentColor => _isZh ? '强调色' : 'Accent';
  String get backgroundColor => _isZh ? '背景色' : 'Background';
  String get surfaceColor => _isZh ? '卡片色' : 'Surface';
  String get editColor => _isZh ? '编辑颜色' : 'Edit Color';
  String get saveThemeScheme => _isZh ? '保存配色' : 'Save Scheme';
  String get presetSpiderVerse => _isZh ? '纵横宇宙' : 'Spider-Verse';
  String get presetMidnightOrchid => _isZh ? '午夜紫' : 'Midnight Orchid';
  String get presetEmberCore => _isZh ? '余烬橙' : 'Ember Core';
  String get presetGlacierMint => _isZh ? '冰川薄荷' : 'Glacier Mint';
  String get presetVoltLime => _isZh ? '电光青柠' : 'Volt Lime';

  String get links => _isZh ? '链接' : 'Links';
  String get projectWebsite => _isZh ? '项目网站' : 'Project Website';
  String get openWebsite => _isZh ? '打开网站' : 'Open Website';
  String get openWebsiteFailed => _isZh ? '无法打开网站' : 'Unable to open website';
  String get dataStorage => _isZh ? '数据' : 'Data';
  String get dataBackup => _isZh ? '备份与恢复' : 'Backup & Restore';
  String get dataBackupHint => _isZh ? '导出本地数据，或从备份文件恢复。' : 'Export local data or restore from a backup file.';
  String get exportBackup => _isZh ? '导出备份' : 'Export Backup';
  String get importBackup => _isZh ? '导入备份' : 'Import Backup';
  String get exportBackupSuccess => _isZh ? '备份已导出' : 'Backup exported';
  String get importBackupSuccess => _isZh ? '备份已导入' : 'Backup imported';
  String get backupActionFailed => _isZh ? '备份操作失败' : 'Backup action failed';
  String get backupChooseFolder => _isZh ? '选择导出位置' : 'Choose export location';
  String get backupChooseFile => _isZh ? '选择备份文件' : 'Choose backup file';
  String get backupNotSupported => _isZh ? '当前平台暂不支持该操作' : 'This action is not supported on the current platform';

  String get appTitle => 'Momentum';
  String get splashSubtitle => _isZh ? '持续向前' : 'KEEP MOVING FORWARD';
}
